server:
  port: 9001
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_1
    username: root
    
  jpa:
    show-sql: true
    
  application:
    name: USER-SERVICE
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
      

    
    