server:
  port: 9002
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_1
    username: root
    password: 
    
  jpa:
    show-sql: true
    
  application:
    name: DEPARTMENT-SERVICE
    
  zipkin:
    base-url: http://127.0.0.1:9411/
    
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

    
    